In [23]:
import numpy as np

In [24]:
python_list=[1,2,3,4,5]
print(f"Python List: {python_list}")

numpy_list=np.array([1,2,3,4,5])
print(f"Numpay list: {numpy_list}")

print("Added 10 in each Element:",[x+10 for x in python_list])

print("Added 10 in numpy list",numpy_list+10)

Python List: [1, 2, 3, 4, 5]
Numpay list: [1 2 3 4 5]
Added 10 in each Element: [11, 12, 13, 14, 15]
Added 10 in numpy list [11 12 13 14 15]


In [25]:
import time

size=1000000
python_list = list(range(size))

numpy_list=np.arange(size)

start=time.time()
result_list=[x+1 for x in python_list]
time_for_python_list=time.time()-start
print(f"The operation was done in: {time_for_python_list:.4f}s")

start=time.time()
result_numpy_list=numpy_list+1
time_for_numpy_list=time.time()-start
print(f"The operation was completed in: {time_for_numpy_list:.4f}s ")
print(f"Numpy is: {time_for_python_list/time_for_numpy_list:.4f}s Faster")


The operation was done in: 0.3978s
The operation was completed in: 0.0107s 
Numpy is: 37.1180s Faster


In [26]:
array=np.linspace(0,1,5)
print(array)

[0.   0.25 0.5  0.75 1.  ]


In [27]:
array=np.full(5,7)
print(array)

[7 7 7 7 7]


In [28]:
identity_martix=np.eye(3)
print(identity_martix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
random=np.random.rand(5)
print(random)

[0.22325686 0.27957829 0.55188895 0.05931343 0.19711991]


In [30]:
random_int=np.random.randint(1,10,size=5)
print(random_int)

[8 1 2 2 1]


In [31]:
print(array.dtype)

int64


In [32]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(np.shape(matrix))

(3, 3)


In [37]:
print(matrix.ndim)

2


In [41]:
print(matrix.size)

9


In [45]:
matrix_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(matrix_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [47]:
print(matrix_3d.shape)
print(matrix_3d.ndim)

(2, 2, 3)
3


In [48]:
print(matrix_3d.itemsize)

8


In [50]:
print(matrix_3d.nbytes)

96


In [ ]:
print(matrix_3d.T)

[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [52]:
print(matrix)
print(matrix[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [54]:
print(matrix[:,1])

[2 5 8]


In [55]:
print(matrix[0,:])

[1 2 3]


In [56]:
print(matrix[0:2,0:2])

[[1 2]
 [4 5]]


In [60]:
print(matrix_3d)
print()
print(matrix_3d[1,0:2,0:2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[ 7  8]
 [10 11]]


In [62]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array[array>5])
print(array[array%2==0])

[ 6  7  8  9 10]
[ 2  4  6  8 10]


In [64]:
print(matrix)
print(matrix[matrix>5])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[6 7 8 9]
