In [1]:
import numpy as np

In [2]:
python_list=[1,2,3,4,5]
print(f"Python List: {python_list}")

numpy_list=np.array([1,2,3,4,5])
print(f"Numpay list: {numpy_list}")

print("Added 10 in each Element:",[x+10 for x in python_list])

print("Added 10 in numpy list",numpy_list+10)

Python List: [1, 2, 3, 4, 5]
Numpay list: [1 2 3 4 5]
Added 10 in each Element: [11, 12, 13, 14, 15]
Added 10 in numpy list [11 12 13 14 15]


In [3]:
import time

size=1000000
python_list = list(range(size))

numpy_list=np.arange(size)

start=time.time()
result_list=[x+1 for x in python_list]
time_for_python_list=time.time()-start
print(f"The operation was done in: {time_for_python_list:.4f}s")

start=time.time()
result_numpy_list=numpy_list+1
time_for_numpy_list=time.time()-start
print(f"The operation was completed in: {time_for_numpy_list:.4f}s ")
print(f"Numpy is: {time_for_python_list/time_for_numpy_list:.4f}s Faster")


The operation was done in: 0.2161s
The operation was completed in: 0.0072s 
Numpy is: 30.0915s Faster


In [4]:
array=np.linspace(0,1,5)
print(array)

[0.   0.25 0.5  0.75 1.  ]


In [5]:
array=np.full(5,7)
print(array)

[7 7 7 7 7]


In [6]:
identity_martix=np.eye(3)
print(identity_martix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
random=np.random.rand(5)
print(random)

[0.91607878 0.71342339 0.50487349 0.11246    0.85153079]


In [8]:
random_int=np.random.randint(1,10,size=5)
print(random_int)

[6 6 9 5 9]


In [9]:
print(array.dtype)

int64


In [10]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(np.shape(matrix))

(3, 3)


In [12]:
print(matrix.ndim)

2


In [13]:
print(matrix.size)

9


In [14]:
matrix_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(matrix_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
print(matrix_3d.shape)
print(matrix_3d.ndim)

(2, 2, 3)
3


In [16]:
print(matrix_3d.itemsize)

8


In [17]:
print(matrix_3d.nbytes)

96


In [18]:
print(matrix_3d.T)

[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [19]:
print(matrix)
print(matrix[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [20]:
print(matrix[:,1])

[2 5 8]


In [21]:
print(matrix[0,:])

[1 2 3]


In [22]:
print(matrix[0:2,0:2])

[[1 2]
 [4 5]]


In [23]:
print(matrix_3d)
print()
print(matrix_3d[1,0:2,0:2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[ 7  8]
 [10 11]]


In [24]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array[array>5])
print(array[array%2==0])

[ 6  7  8  9 10]
[ 2  4  6  8 10]


In [25]:
print(matrix)
print(matrix[matrix>5])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[6 7 8 9]


In [26]:
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])
print(array1+array2)

[ 7  9 11 13 15]


In [27]:
print(array1-array2)

[-5 -5 -5 -5 -5]


In [28]:
print(array1*array2)

[ 6 14 24 36 50]


In [29]:
print(array1/array2)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [30]:
print(np.sqrt(array1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [31]:
print(array1>2)

[False False  True  True  True]


In [36]:
reshape_array1=array1.reshape(5,1)
print(reshape_array1)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [42]:
auto_reshape=array1.reshape(1,-1)
print(auto_reshape)

[[1 2 3 4 5]]


In [47]:
print(array1)
print(array2)
print()
print(np.vstack((array1,array2)))
print()
print(np.hstack((array1,array2)))

[1 2 3 4 5]
[ 6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 1  2  3  4  5  6  7  8  9 10]


In [49]:
print(np.sum(np.vstack((array1,array2)),axis=0))

[ 7  9 11 13 15]
